# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tHzVGWn2epw4HTNaArKrXC4W8z06_8fZ
"""

import pandas as pd

# Cargar el archivo CSV en un DataFrame de Pandas
archivo_csv = 'base presencia en la cultura popular limpio.csv'
df = pd.read_csv(archivo_csv, sep=';')

# Visualizar las primeras 5 filas de la base de datos
df.head()