# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kU0mMy1a5avmrnjjoRjYDjy4WUWOHNoY
"""

import pandas as pd

# Cargar el archivo CSV en un DataFrame de Pandas
df = pd.read_csv('base carrera musical (álbumes) LIMPIO.csv', sep=';')

# Visualizar las primeras 5 filas de la base de datos
df.head()